config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'work', to: 'pages#work'
  get 'skills', to: 'pages#skills'
  get 'contact', to: 'pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end

  def work
  end

  def skills
    @skills = ["Ruby", "Ruby on Rails", "HTML", "CSS", "Javascript", "jQuery",
              "Ajax", "PostgreSQL", "MySQL", "Git", "GitHub", "Heroku", "AWS",
              "S3", "Docker", "React", "API", "Rspec"]

  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/header' %>
    <%= render 'shared/navigation' %>
    <%= render 'shared/flashes' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/contact.html.erb
<div id="contact">
  Email me at <b><%= mail_to "alyssa.biot@gmail.com" %></b>
</div>

app/views/pages/home.html.erb
<div id="home">
  HOME
</div>

app/views/pages/skills.html.erb
<div id="skills">
  <ul class="list-unstyled list-inline">
    <% @skills.each do |skill| %>
      <li class="skill-btn"><%= skill %></li>
    <% end  %>
  </ul>
</div>

app/views/pages/work.html.erb
<div id="work">
  <!--  TO DO : add carousel view-->
  <div class="carousel">
    <% ["Project1", "Project2", "Project3", "Project4"].each do |project| %>
      <div class="card">
        <%= project %>
      </div>
    <% end  %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div id="header">
  <h1><%= link_to "Alyssa Biot", root_path %></h1>
</div>

app/views/shared/_navigation.html.erb
<div id="navigation">
  <h4>
    <%= link_to "work", work_path %>
    -
    <%= link_to "skills", skills_path %>
    -
    <%= link_to "contact", contact_path %>
  </h4>
  <hr>
</div>